# https://github.com/hurlenko/filebrowser-docker/tree/master
# https://github.com/Haxxnet/Compose-Examples/blob/main/examples/filebrowser/docker-compose.yml
services:
  filebrowser:
    build:
      context: .
      dockerfile: Dockerfile
    image: filebrowser
    container_name: filebrowser
    ports:
      - 8080:80
#    volumes:
#      - ${DOCKER_VOLUME_STORAGE:-/.}/data:/data
#      - ${DOCKER_VOLUME_STORAGE:-/.}/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
