# https://github.com/hurlenko/filebrowser-docker/tree/master
# https://github.com/Haxxnet/Compose-Examples/blob/main/examples/filebrowser/docker-compose.yml
services:
  filebrowser:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.alpine
    image: thevickypedia/filebrowser
    container_name: filebrowser
    ports:
      - 8080:80
    volumes:
      # Bind mount for persistent storage and config
      # export DOCKER_VOLUME_STORAGE=$(pwd)
      - "${DOCKER_VOLUME_STORAGE:-$HOME}:/data"
      - "${DOCKER_VOLUME_STORAGE:-$HOME/.filebrowser}/config:/config"
    restart: unless-stopped
