---
name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
  release:
    types:
      - published

env:
  repository: ${{ github.repository || 'thevickypedia/filebrowser' }}
  repository_name: ${{ github.repository.name || 'filebrowser' }}
  repository_description: ${{ github.event.repository.description || 'ðŸ“‚ Web File Browser' }}
  release_tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag_name }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Tags
        run: |
          if [ -z "${{ env.release_tag_name }}" ]; then
            echo "::warning title=Missing Tag::Release tag name is not set, using ONLY 'latest' as tag."
            tags="${{ env.repository }}:latest"
          else
            tags="${{ env.repository }}:latest,${{ env.repository }}:${{ env.release_tag_name }}"
          fi
          echo "Docker image will be pushed with tags: ${tags}"
          echo "DOCKER_TAGS=${tags}" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: thevickypedia/docker/base/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_TAGS }}

      - name: Update description
        uses: thevickypedia/describe-docker@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          summary: "${{ env.repository_description }}"
          repository: "${{ env.repository_name }}"
          filename: "README.md"
